services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-render-o8u4.onrender.com
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PROTOCOL
        value: http
      - key: N8N_PORT
        value: 10000
